### ISSUE TITLE
1520ID and robot tool attachment problem

### ISSUE THREAD

**Issue by GMOnder01** [RobotComponents/RobotComponents#106]
Dear RobotComponents Team,

Firstly, thank you for this awesome ABB tool for grasshopper. I'm trying to implement 1520ID welding robot to your plug-in (uploaded the files). As you can see from the screenshot image, tool is not attached to robot while following the path. Maybe you can show me where im missing. Thank you a lot. Best Regards.

Gani Melik Onder (https://www.linkedin.com/in/ganimelikonder/)
R&D Engineer from AlloyAdditive

[1520ID.zip](https://github.com/RobotComponents/RobotComponents/files/7763294/1520ID.zip
![1520ID](https://user-images.githubusercontent.com/55344585/147110767-c38c93b7-6714-4226-aed0-571650cd97c7.JPG)

**Comment by arjendeetman** [comment]
Dear Gani,

Please see the files below. I don't know what the issue was, but I took the example file and just filled in all the values for the IRB1520ID and it worked... In your file, I saw a few mistakes in setting up the axis plane (all y-values should be zero) and I think there was an issue with the orientation of the attachment plane. 

[1520ID - arjen.zip](https://github.com/RobotComponents/RobotComponents/files/7763942/1520ID.-.arjen.zip)

In the next release, I will add this robot as a preset. As a reminder, I will leave this issue open until I added it. 

Best,

Arjen

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)

**Comment by GMOnder01** [comment]
Thank you Arjen. I have one follow-up question. My custom robot position doesn't move with changing the position plane while predefined robots can easily be moved. How can i overcome this problem?

**Comment by arjendeetman** [comment]
If you set up a custom robot and you move the positioning plane you also have to move the axis planes, geometry, mounting frame, etc. 

I thought I implemented transformation methods in the Robot parameter, but I realize now I only did this for the external axes. For the Robot, transformation methods are only available in the API. I will also change this in the next release. Then it becomes easier. In that case, you can define everything for a position plane equal to the default world XY plane and orient, move, or use any other transformation method to move it to the new position. It is an easy fix. As said, I will add this...

![image](https://user-images.githubusercontent.com/20628133/147260567-cb73ca4a-283d-4e9b-8601-d6d80fb8ff81.png)

**Comment by arjendeetman** [comment]
I jus released a new version with the IRB1520ID as a robot preset. I also added the transformation methods to the robot parameter.
