### ISSUE TITLE
Add MoveC to the robot movement types

### ISSUE THREAD

**Issue by Coroush** [RobotComponents/RobotComponents#122]
Hi, would it be possible to use Circular Move as a movement type?

**Comment by arjendeetman** [comment]
I think we can implement this. It is basically the same as a MoveL or MoveJ instruction we only need to define the circle point (as a robot target). 

What I would suggest is to add this functionality to the current Move component. We can add MoveC to the value list with movement types. If MoveC is selected an additional input parameter will appear for defining the circle point. If another movement type is selected this input parameter will automatically be removed. I only need to figure out and test how the tool orientation is interpolated between the targets (for our path generator). 

[] Add MoveC to the movement types
[] Add the CirclePoint property to the Movement base class
[] Adjust the methods that generate the RAPID code line
[] Add MoveC to the path generator

If we implement this it will probably be somewhere at the beginning of next year. Somewhere between January and March.  I am working on some other new functions that I want to finalize first. 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)

**Comment by arjendeetman** [comment]
@Coroush I had a look at the implementation of MoveC. I could implement it, only the interpolation of the tool between the two targets is not correct yet. Thus, the path generator doesn't give a correct result. Do you know how the tool orientation is interpolated for MoveC? 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)

**Comment by Coroush** [comment]
Hi @arjendeetman, Many thanks for having a look at this!
Unfortunately, I haven't tried re-orientation since I am using MoveC in a milling task. here I'm attaching a simple script, with the MoveC that I could generate by postprocessing the g-code (using RobotComponents).
[robotCircleTest.zip](https://github.com/RobotComponents/RobotComponents/files/10786663/robotCircleTest.zip)

I could find these references in the RAPID manual that may be helpful. CirPathMode (page 40) and MoveC Instructions (page 241) 
https://robotum.cz/wp-content/uploads/2019/10/Technical-reference-manual_RAPID_3HAC16581-1_revJ_en.pdf

thanks again,

**Comment by arjendeetman** [comment]
Hi @Coroush. 

I found the same documentation but that didn't make it clear to me... I will see if I can also add a component for the CirPathMode and see if I can make the path generator correct for PathFrame, ObjectFrame (this one should be easy since it is the same interpolation as for MoveL), and CirPointOri (should be easy if we know how PathFrame functions). If it will take too much time, I will release it without a correct implementation in the path generator and raise a warning if MoveC instructions are passed to the path generator. I can already write proper RAPID code with the RAPID generator without using Python components, which will make your file already much cleaner :) 

@ar0551 Do you have any experience with MoveC instructions and maybe know how the tool orientation is interpolated for MoveC instructions? 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)

**Comment by arjendeetman** [comment]
Hi @Coroush. 

I already finished the implementation of MoveC a while ago. However, I cannot completely figure out how ABB does the interpolation for all the Circle Path Modes. Since I have limited time, I decided to anyway release it. 

MoveC is released in v2.2.0. However, the path generator does an approximation for the modes 'PathFrame' and 'CirPointOri'. For the mode 'ObjectFrame' the generated path is correct. Generating the RAPID code is fully supported. The best is to use Robot Studio for an accurate simulation. 

I will close this issue. As a reminder to improve the path generator, I made a new issue (https://github.com/RobotComponents/RobotComponents/issues/159). 

Best,

Arjen 

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K1791RX)
