### ISSUE TITLE
Configuration Data

### ISSUE THREAD

**Issue by xPhilippeRoux** [RobotComponents/RobotComponents#182]
I believe there is something with the Configuration Data [cf1, cf4, cf6, cfx]. No matter which value I define, it gets associated with cfx, whereas cf1/cf4/cf6 stay at 0. The IK however works fine, but quadrants are not updated with their value (see below, where cf1 & cf6 should be both -1). I avoid the issue with a ConfL\Off, but I prefer not to.

![image](https://github.com/user-attachments/assets/1d04911c-e3c8-453d-ad2b-95c8e064ee24)

**Comment by arjendeetman** [comment]
Hi @xPhilippeRoux, 

Can you show me the target component as well where you define the configuration data? Are you using a number input (will be casted to cfx and the other values set to 0) or a configuration data component? 

Best, 

Arjen

**Comment by xPhilippeRoux** [comment]
Hi @arjendeetman,

I didn't save the example but yes I am using a number input (casted to configuration data). As you say the value is accepted and casted to cfx while keeping the other at 0, which does not represent real life. When exporting to a robot, it says that the target is not reachable, unless we stop reading configuration (ConfL\Off).

I have seen the configuration data component but I cannot assign cf1/cf4/cf6 manually, before performing IK. I would assume the code generation to calculate it for me while performing the IK. Or should I run the IK in parallel and calculate the quadrants in parallel ? Do you have an example of use for that ?

Best,

Philippe

**Comment by arjendeetman** [comment]
Why do you wanna define cf1, cf4 and cf6? Is that required for the robot you are using? If you have a typical spherical wrist robot there are 8 solutions. You can pick one of these with cfx. What is the benefit of using the other cf parameters? Is it the case that if you have, for example, cfx=2 and you want to define cf6 since the 6th axis can for instance rotate from -400 till 400 degrees? Thus, cfx=2 has multiple solutions since the 6 axis can be, for instance, -350, 10 and 370 degrees?

**Comment by xPhilippeRoux** [comment]
I want to define them just because it is required. Otherwise the robot gives an error, saying it can't reach the target with the specified configuration.

Yet I agree with the theory, I know there are only 8 solutions, and among that, only 2 that interest me. I know that cfx has 8 different possibilities to match that, however cf1/cf4/cf6 need to be specified in their corresponding quadrant (unless ignoring configuration values with ConfL\Off). See below the extract of RobotStudio documentation : 
![image](https://github.com/user-attachments/assets/4bfd053b-68f5-44de-ab59-841ec2fc4238)

I'm thinking that perhaps ABB uses it like that to enhance embedded calculations. I may be wrong.
The only way not to get stuck right now is to ignore configuration, but I know it is not advised as it may behave not as simulated.

**Comment by arjendeetman** [comment]
Note: related to issue https://github.com/RobotComponents/RobotComponents/issues/181

**Comment by arjendeetman** [comment]
I don't know yet what a good work flow could be for this issue. For now, could you use the inverse kinematics component to get the joint positions. From this get the cf values and use them to create a configuration data for the robot target? What possible issues would you get here? Since I would probably get the same issues when I try to implement it.. 

Best, 

Arjen

**Comment by xPhilippeRoux** [comment]
Yes it is exactly what I imagine to do, yet it will increase computation time a lot for nothing. Even considering your intermediate solution.

The easiest for me is to apply ConfL\Off and figure out the cases where it can be problematic.

Have you tested generating and running toolpaths with linear motions & ConfL\On ? I am sure this need is common for a lot of users.

Best,

Philippe

**Comment by arjendeetman** [comment]
About this: "Have you tested generating and running toolpaths with linear motions & ConfL\On". 

I always use ConfL\On if needed but I try to avoid ConfJ\On. To move to the start location I sometimes adjust the cfx value of that first joint movement if problems arise but that rarely happens. As far as I know, other users do the same... 

I find the workflow complicated to define the other cf values. That means that for every robot target, you need to perform an ik. It is a simple ik and doesn't take so much time, but still...  

This: "I want to define them just because it is required." That is the case for the IRB8700, not the other robots? That might be the reason no other user asked for this option/workflow.

Best,

Arjen

**Comment by arjendeetman** [comment]
Hi @xPhilippeRoux,

I'm sorry; it was my fault. I swapped the two. I use `ConfLOff` and `ConfJOn` (avoid `ConfJ/off`).

I also came to a conclusion after reading more about the configuration data in the documentation. There is no issue with the configuration data itself, only with the inverse kinematics solver. Let me explain:

When you use a number as input this value will be cast to cfx. The inverse kinematics solver and also the path generator will select this configuration. Unless in the path generator if you use ConfL\Off or ConfJ\Off it will go through all possible poses and select the closest to the current pose. This is implemented at best. At best, since we don't have access to the solvers of ABB. 

There is a Configuration Data component where you can define cf1, cf4, cf6 and cfx. So you can write RAPID code with Robot Components in the correct format. The real issue is that the kinematics solver - the inverse kinematics and path generator component - is ignoring cf1, cf4 and cf6. So, I need to update the solver so the correct configuration is displayed when cf1, cf4 and cf6 are defined. From what I could find, if cf1, cf4 and cf6 are defined these values will be used. If there is no matching configuration with the defined values, cfx will be used instead. The documentation of ABB is a bit vague. To be sure I need to check this with Robot Studio. 

If the above is implemented Robot Components will always display the correct configuration if you define cf1, cf4 and cf6. This will give you more control over the configuration, something you want. How to obtain the values cf1, cf4 and cf6 is a completely different discussion. From my perspective, this is user and application-dependent. 

Best,

Arjen

**Comment by arjendeetman** [comment]
I did the check in Robot Studio. In the other issue, you wrote the problem occurred on an IRB6620-150/2.2 so I used this one. From what I observed, it first considers cfx and after it checks if it is possible to maintain this configuration with the quadrants defined by cf1, cf4 and cf6. 

As example. I defined a robot target and the result is a certain joint position with joint angle 4 in quadrant 2. This could also be quadrant -2 (-360 degrees) since this will visually give the same pose. If I define cfx the same and cf4 as -2 it will move to this pose with joint 4 in quadrant -2. However, when I define the quadrants for cf1, cf4 and cf6 as they should be for cfx is 1, but I set cfx to for example to 6. It will move to the configuration that belongs to cfx is 6. My conclusion is it only uses cf1, cf4 and cf6 to 'fine tune' the pose it gets for the given cfx. If will ignore the values for cf1, cf4 an cf6 if they are incorrect. It can for instance only reach the target when cf4 is -2 or 2 for a given cfx. If the value is set to -3 it will simply ignore it. 

Another example, for a given robot target, for cfx is 3, the quadrants of joint 1, 4, and 6 are -1, -1, and 2 for the pose it reaches. If I now set the configuration data for the same target as [-1, -1, 2, 0] this results in a pose with the quadrants of joint 1, 4, and 6 in -1, 0 and 3. Thus completely ignoring cf1, cf4 and cf6, and only considering cfx. So, cfx is the leading parameter. 

So, for a spherical wrist robot, to update the inverse kinematics solver of Robot Components I need to take into account the values provided for cf1, cf4 and cf6 as follows:

- First, calculate the pose for the given cfx as we do now.
- Second, check if the provided quadrants of cf1, cf4 and cf6 are within the solution for the given cfx by adding or subtracting 360 degrees from the calculated solution. If so, use this quadrant and correct the joint position with either -360 or +360 degrees.

This is what I observed for a spherical wrist robot. Still need to check a P-rod robot like the IRB8700.

Best,

Arjen

**Comment by arjendeetman** [comment]
I also quickly checked the P-rod robot (IRB8700). For this robot, first cf1, cf4 and cf6 are considered. This is when the parameter `Use cfx for robot targets for P-rod robots` is set to False (default). If this parameter is set to True, it will behave exactly the same as for a spherical wrist robot with cfx as a leading parameter. 

You can change the parameter in the controller: Configuration -> Motion -> Robot -> last parameter in the list. You need to restart the controller when you change it.

Best,

Arjen

**Comment by xPhilippeRoux** [comment]
Very detailed answer, thanks for that !

If I follow you, I should not have been stuck with my IRB 6620, as it should have ignored cf1/cf4/cf6 and use the value of cfx, which was correct. Yet it would not perform the traject, due to impossible configuration. It will thus be the same anyway if I change the `Use cfx for robot targets for P-rod robots` for my IRB 8700.

I understand that unless I am able to compute those 3 values in a reasonable time, I need to use the `ConfL\Off`. It is not the case right now, but I am not sure that this is so application-dependent. I mean, of course it depends, but I also think that there is a generic answer that will work in most of the cases (the closest value for axis 1/4/6 while performing IK or path generator).

Best,

Philippe

**Comment by xPhilippeRoux** [comment]
The target was actually totally reachable, and the cfx was correct as well. I just added a `ConfL\Off` at the beginning and it worked.

I totally agree with your will to keep it as user-friendly as possible, and I am used with those constraints. The good thing is that you manipulate extendable components, where advanced users can extend according to their need. The best example is the `Path Generator`, where a lot of outputs can be selected. Adding the right configuration data seems a good solution to me, and not too complicated as robot joint positions are already computed.

From my point of view, it would be important to overwrite configuration data as an option in the `RAPID Generator` as well.

Best,

Philippe

**Comment by arjendeetman** [comment]
I made some changes in the new release, https://github.com/RobotComponents/RobotComponents/releases/tag/v3.1.2. They all improve the visualization and approximation of the Path Generator component, but it is still not perfect. It is a beginning. 

It is difficult to determine exactly what behavior ABB implemented. It does not always behave as I expected.

**Comment by xPhilippeRoux** [comment]
That would be perfect indeed. 

Again, congratulations on your work !

**Comment by arjendeetman** [comment]
Hi @xPhilippeRoux,

The path generator and ik components should behave correctly now after the last release. From my perspective it behaves as it should. We don't calculate cf values for the users at the moment. The user should provide them but I can add tools that can help with this. I opened separate issues for them: https://github.com/RobotComponents/RobotComponents/issues/184 https://github.com/RobotComponents/RobotComponents/issues/185

Other suggestions are welcome. For now, since it behaves as it should, I would like to close this issue.

Best,

Arjen

**Comment by xPhilippeRoux** [comment]
Hi @arjendeetman,

No worries you can close the issue, my point is now contained within issue #185. 

Best,

Philippe
